spring:
  liquibase:
    change-log: classpath:/db/changelog-profiles/changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
server:
  port: 8861
eureka:
  instance:
    appname: main-app
  client:
    registerWithEureka: false
    fetchRegistry: false